services:
  front:
    build: ./front
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    build: ./api
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"